category = Category.create(name: "Life Events")
category = Category.create(name: "Restaurants")
category = Category.create(name: "Stores")
category = Category.create(name: "Locations")
category = Category.create(name: "Items")

subject = Subject.create(category_id: 1, average_rating: 3.0, description: "Description")
subject = Subject.create(category_id: 2, average_rating: 3.0, description: "Description")
subject = Subject.create(category_id: 3, average_rating: 3.0, description: "Description")
subject = Subject.create(category_id: 4, average_rating: 3.0, description: "Description")
subject = Subject.create(category_id: 5, average_rating: 3.0, description: "Description")
